### ISSUE TITLE
能在 Readme 中写一个“快速入门” 或者 “How to” 章节吗？

### ISSUE THREAD

**Issue by Bian-Sh** [TheSakuraCherry/MMDarknessTimeline#1]
现在，我使用 unity 2021.3.38f1 创建常规3d工程，然后导入你的插件到 Assets 文件夹，再导入 Odin ，然后开启示例，并不能用，发现以下问题：
1. Camera 和Directional Light 组件上有脚本丢失
3. 场景 shader 丢失满屏幕粉色
4. 不 Play 时开启你的 TimeLine,通过首页“选择时间轴”开启示例提供的 timeline 文件， 会报下面的错误
![image](https://github.com/user-attachments/assets/2b686829-b51f-4cef-a78d-5fcea2023759)

6. Play 示例场景报以下错误
![image](https://github.com/user-attachments/assets/4ef73ea7-a6d3-488b-8ec9-0ff100a138b5)

SO....如果你能跑通从新建工程👉导入插件👉导入 Odin 👉打开窗口并正常 Play 示例并把这个操作写到 Readme 就好了

**Comment by TheSakuraCherry** [comment]
你好，我的项目是默认URP项目，可以用URP打开场景试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月18日(周三) 上午10:44
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [TheSakuraCherry/MMDarknessTimeline] 能在 Readme 中写一个“快速入门” 或者 “How to” 章节吗？ (Issue #1)




 
现在，我使用 unity 2021.3.38f1 创建常规3d工程，然后导入你的插件到 Assets 文件夹，再导入 Odin ，然后开启示例，并不能用，发现以下问题：
  
 
Camera 和Directional Light 组件上有脚本丢失
 
 
 
场景 shader 丢失满屏幕粉色
 
 
 
不 Play 时开启你的 TimeLine,通过首页“选择时间轴”开启示例提供的 timeline 文件， 会报下面的错误
 image.png (view on web)
 
 
 
Play 示例场景报以下错误
 image.png (view on web)
 
  
SO....如果你能跑通从新建工程👉导入插件👉导入 Odin 👉打开窗口并正常 Play 示例并把这个操作写到 Readme 就好了

**Comment by Bian-Sh** [comment]
OK，换了 URP，能够正常显示场景和角色了，但是这个 Sample 还是跑不通。
建议还是你还是新建工程走一遍流程出一个 how to

**Comment by TheSakuraCherry** [comment]
什么版本的编辑器？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月18日(周三) 晚上6:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TheSakuraCherry/MMDarknessTimeline] 能在 Readme 中写一个“快速入门” 或者 “How to” 章节吗？ (Issue #1)




 
OK，换了 URP，能够正常显示场景和角色了，但是这个 Sample 还是跑不通。
 建议还是你还是新建工程走一遍流程出一个 how to

**Comment by TheSakuraCherry** [comment]
我建议不要更换unity版本再试试，因为是基于nobug的编辑器，原生的不支持低版本unity的话我也没办法了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月18日(周三) 晚上6:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TheSakuraCherry/MMDarknessTimeline] 能在 Readme 中写一个“快速入门” 或者 “How to” 章节吗？ (Issue #1)




 
OK，换了 URP，能够正常显示场景和角色了，但是这个 Sample 还是跑不通。
 建议还是你还是新建工程走一遍流程出一个 how to

**Comment by Bian-Sh** [comment]
"nobug的编辑器 " 是个啥意思啊？ 我用的是 Unity2021.3.38f1

**Comment by TheSakuraCherry** [comment]
b站搜一搜nobug技能编辑器



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月19日(周四) 下午2:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TheSakuraCherry/MMDarknessTimeline] 能在 Readme 中写一个“快速入门” 或者 “How to” 章节吗？ (Issue #1)




 
"nobug的编辑器 " 是个啥意思啊？ 我用的是 Unity2021.3.38f1
